services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: asdf1234
      MARIADB_DATABASE: relay
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=asdf1234"]

  relay-backend:
    build: ./relay-backend
    container_name: relay-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/relay?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: asdf1234

  relay-frontend:
    build:
      context: ./relay-frontend
      args:
        - API_URL=http://localhost:8080
    container_name: relay-frontend
    restart: always
    depends_on:
      - relay-backend
    ports:
      - "80:80"

volumes:
  mariadb_data:
